{% set name = "sql-parser" %}
{% set version = "3.7.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/cill-airne/sql-parser.git
  git_depth: 1 # (Defaults to -1/not shallow)

build:
  noarch: generic
  number: 1

requirements:
  build:
    - cmake
    - make  # [unix]
    - {{ compiler('cxx') }}
    - bison=3

about:
  summary: 'SQL'
  description: 'SQL'
